### ISSUE TITLE
Issue With Hiding Script Commands On Items.

### ISSUE THREAD

**Issue by TheLuckyIrish96** [XHawk87/CreateYourOwnMenus#39] opened 2020-10-23 17:30 UTC
When using the "/menu script add" command to a item, after adding a command for example "/menu script add /time set day", when I try to use the command "/menu script hide" it works successfully but when I try to execute the command scripted to the item the "/hide" command has removed letters from the typed command. For example when I did "/menu script add /heal @p" when I hid the script it would try to execute the command as "/menu script add /hal @p". Is this a known bug for the most current version?

**Comment by XHawk87** [comment] 2020-10-23 17:33
Duplicate of #36

**Closed by XHawk87** 2020-10-23 17:33 UTC
